import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 16, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#64748b", marginBottom: 16 },
  table: { display: "flex", flexDirection: "column", borderWidth: 1, borderColor: "#e2e8f0" },
  row: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#e2e8f0" },
  headerRow: { backgroundColor: "#f1f5f9" },
  cell: { padding: 6, flex: 1, borderRightWidth: 1, borderColor: "#e2e8f0" },
  cellHeader: { padding: 6, flex: 1, borderRightWidth: 1, borderColor: "#e2e8f0", fontWeight: 700 },
  lowAttendance: { color: "#dc2626", fontWeight: 700 },
});

interface AttendanceRow {
  studentId: string;
  name: string;
  present: number;
  late: number;
  excused: number;
  absent: number;
  total: number;
  pct: number;
}

export async function renderAttendancePdf(title: string, rows: AttendanceRow[]): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>Generated by EM&amp;TL E1 Faculty Admin Panel · {new Date().toLocaleDateString()}</Text>
        <View style={styles.table}>
          <View style={[styles.row, styles.headerRow]}>
            <Text style={styles.cellHeader}>Student ID</Text>
            <Text style={styles.cellHeader}>Name</Text>
            <Text style={styles.cellHeader}>Present</Text>
            <Text style={styles.cellHeader}>Late</Text>
            <Text style={styles.cellHeader}>Excused</Text>
            <Text style={styles.cellHeader}>Absent</Text>
            <Text style={styles.cellHeader}>Sessions</Text>
            <Text style={styles.cellHeader}>Attendance %</Text>
          </View>
          {rows.map((r) => (
            <View style={styles.row} key={r.studentId}>
              <Text style={styles.cell}>{r.studentId}</Text>
              <Text style={styles.cell}>{r.name}</Text>
              <Text style={styles.cell}>{r.present}</Text>
              <Text style={styles.cell}>{r.late}</Text>
              <Text style={styles.cell}>{r.excused}</Text>
              <Text style={styles.cell}>{r.absent}</Text>
              <Text style={styles.cell}>{r.total}</Text>
              <Text style={[styles.cell, r.pct < 80 ? styles.lowAttendance : {}]}>{r.pct}%</Text>
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );

  return renderToBuffer(doc);
}
